name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install
          mkdir -p www
          cp public/index.html www/

      - name: Build Android Project
        run: |
          npx cap add android
          npx cap sync
          cd android && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GeoMetka-Release
          path: android/app/build/outputs/apk/debug/app-debug.apk
